[tool.black]
line-length = 110


extend-exclude = '''
(
	\/migrations\/
)
'''

[[tool.mypy.overrides]]
module = 'parameterized.*'
ignore_missing_imports = true


[[tool.mypy.overrides]]
module = 'openmock.*'
ignore_missing_imports = true
