[tool.black]
line-length = 110


extend-exclude = '''
(
	\/migrations\/
)
'''

[[tool.mypy.overrides]]
module = 'parameterized.*'
ignore_missing_imports = true


[[tool.mypy.overrides]]
module = 'opensearch_dsl.*'
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = 'elasticmock.*'
ignore_missing_imports = true