# Workflow for running unit tests of Python files.
name: Python Tests

on: [pull_request]

jobs:
  test:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python Environemnt
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Requirements
        run: |
          pip install -r requirements.txt
          pip install -r requirements_tests.txt

      - name: Run Tests
        run: |
          ./run_tests.sh
