name: Python Static Analyzers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Python Static Analyzers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python Environemnt
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Requirements
        run: |
          make install_requirements

      - name: Run Analyzers
        run: |
          make check
